name: Create Version and Tag
# If you change this name, don't forget to change the name in 'deploy.yml'!

on:
  schedule:
    - cron: '0 * * * *'  # every hour

jobs:
  calculate-version-and-tag:
    name: Calculate Version and Create Tag
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'zulu'
          cache: 'sbt'

      - name: Set up NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: '12.x'

      - name: Bump version using sbt
        id: set-version
        run: |
          # Capture the output
          new_version=$(sbt 'bumpVersion' -error)

          # Trim leading and trailing whitespace (including newlines)
          new_version=$(echo "$new_version" | sed -e 's/^[[:space:]]*//' -e 's/[[:space:]]*$//')

          # NOTE: For testing :)
          echo "New version := ${new_version}"

          # Check that the new_version is actually non-empty and looks like a version number
          if [[ ! $new_version =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
            echo "Error: Version bump failed. Invalid version number: '${new_version}'"
            exit 1
          fi

          echo "VERSION=${new_version}" >> $GITHUB_ENV
          echo "Successfully set new version: ${new_version}"

      - name: Update NPM and MVN versions via sbt
        run: sbt updateVersions

      - name: Commit and push changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "github-actions[bot]"
          git add build.sbt
          git add package.json
          git add pom.xml
          git commit -m "Bump version to ${{ steps.set-version.outputs.VERSION }}"
          git push

      - name: Create and push tag
        run: |
          git tag v${{ steps.set-version.outputs.VERSION }}
          git push origin v${{ steps.set-version.outputs.VERSION }}
