name: Create Version and Tag
# If you change this name, don't forget to change the name in 'deploy.yml'!

on:
  schedule:
    - cron: '0 3,11,15,19 * * *'  # every day at 03:00, 11:00, 15:00, 19:00 UTC
  workflow_dispatch: # For manual triggering

jobs:
  run-tests: # redux of usual CI defined in `ci.yml`
    name: Run tests
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        java-version: '11'
        distribution: 'zulu'

    - name: Set up NodeJS
      uses: actions/setup-node@v4
      with:
        node-version: '12.x'

    - name: Install MLton
      run: |
        curl -L https://github.com/MLton/mlton/releases/download/on-20210117-release/mlton-20210117-1.amd64-linux-glibc2.31.tgz --output mlton.tgz
        tar -xzf mlton.tgz
        mv mlton-20210117-1.amd64-linux-glibc2.31 $GITHUB_WORKSPACE/mlton
        chmod +x $GITHUB_WORKSPACE/mlton/bin/mlton
        echo "Trying to call directly"
        $GITHUB_WORKSPACE/mlton/bin/mlton
        echo "Adding mlton to path"
        echo "$GITHUB_WORKSPACE/mlton/bin" >> $GITHUB_PATH

    - name: Install Chez Scheme, LLVM & libuv
      run: sudo apt-get install -y chezscheme llvm-15 libuv1-dev

    - name: Run tests
      run: sbt clean test

  calculate-version-and-tag:
    name: Calculate Version and Create Tag
    runs-on: ubuntu-latest
    needs: [run-tests]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 11
        uses: actions/setup-java@v4
        with:
          java-version: '11'
          distribution: 'zulu'
          cache: 'sbt'

      - name: Set up NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: '12.x'

      - name: Bump version using sbt
        id: set-version
        run: |
          # Capture the output of 'sbt bumpMinorVersion'
          full_output=$(sbt 'bumpMinorVersion' -error)

          # Extract the version number using grep
          new_version=$(echo "$full_output" | grep -oE '[0-9]+\.[0-9]+\.[0-9]+' | tail -n 1)

          # Trim any potential whitespace
          new_version=$(echo "$new_version" | xargs)

          # Check that the new_version is actually non-empty and looks like a version number
          if [[ ! $new_version =~ ^[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
            echo "Error: Version bump failed. Invalid version number: '${new_version}'"
            echo "Full output was:"
            echo "$full_output"
            exit 1
          fi

          echo "VERSION=${new_version}" >> $GITHUB_OUTPUT
          echo "Successfully set new version: ${new_version}"

      - name: Update NPM and MVN versions via sbt
        run: sbt updateVersions

      - name: Commit and push changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "github-actions[bot]"
          git add project/EffektVersion.scala
          git add package.json
          git add pom.xml
          git commit -m "Bump version to ${{ steps.set-version.outputs.VERSION }}"
          git push

      - name: Create and push tag
        run: |
          git tag v${{ steps.set-version.outputs.VERSION }}
          git push origin v${{ steps.set-version.outputs.VERSION }}
