# This is a copy-and-paste version of ci.yml but additionally creating a release
name: Release Artifacts

on:
  push:
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10
  workflow_run:
    workflows: ["Create Version and Tag"] # 'autorelease.yml'
    types:
      - completed

jobs:
  build-jar:
    name: Build the Effekt compiler and run tests
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.get_version.outputs.VERSION }}

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: 'true'

    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '12.x'

    - name: Install MLton
      run: |
        curl -L https://github.com/MLton/mlton/releases/download/on-20210117-release/mlton-20210117-1.amd64-linux-glibc2.31.tgz --output mlton.tgz
        tar -xzf mlton.tgz
        mv mlton-20210117-1.amd64-linux-glibc2.31 $GITHUB_WORKSPACE/mlton
        chmod +x $GITHUB_WORKSPACE/mlton/bin/mlton
        echo "Trying to call directly"
        $GITHUB_WORKSPACE/mlton/bin/mlton
        echo "Adding mlton to path"
        echo "$GITHUB_WORKSPACE/mlton/bin" >> $GITHUB_PATH

    - name: Install Chez Scheme
      run: sudo apt-get install chezscheme

    - name: Get the version
      id: get_version
      run: echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_OUTPUT

    - name: Run tests and assemble jar file
      run: sbt clean deploy

    - name: Generate npm package
      run: mv $(npm pack) effekt.tgz

    - name: Upload Effekt binary
      uses: actions/upload-artifact@v3
      with:
        name: effekt
        path: bin/effekt

    - name: Upload the npm package
      uses: actions/upload-artifact@v3
      with:
        name: effekt-npm-package
        path: effekt.tgz

  release:
    name: Create Release
    runs-on: ubuntu-latest
    needs: [build-jar]
    steps:
      - name: Download JAR artifact
        uses: actions/download-artifact@v3
        with:
          name: effekt
          path: distribution/

      - name: Download npm package
        uses: actions/download-artifact@v3
        with:
          name: effekt-npm-package
          path: distribution/

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          release_name: Release ${{ needs.build-jar.outputs.version }}
          tag_name: v${{ needs.build-jar.outputs.version }}
          draft: false
          prerelease: false

      - name: Upload jar file
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./distribution/effekt
          asset_name: effekt.jar
          asset_content_type: application/java-archive

      - name: Upload npm package
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./distribution/effekt.tgz
          asset_name: effekt.tgz
          asset_content_type: application/gzip
